## Load data

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/phân cụm/daxuly_co _chuatotnghiep.csv')

In [ ]:
df_diem = df[['mssv', 'diemnamhoc1',	'diemnamhoc2',	'diemnamhoc3',	'diemnamhoc4',	'diemnamhoc5',	'diemnamhoc6',
              'drlnam1', 'drlnam2', 'drlnam3', 'drlnam4', 'drlnam5', 'drlnam6', 'label']]

In [ ]:
df_diem.head(5)

mssv  diemnamhoc1  diemnamhoc2  \
0  BE375BAAXPvAibaEXe9JDlHA4z2GHJ3/PVStCxR2         6.47         6.66   
1  2420ED57XPvAibaEXe/Lh6v1XxTKJa6JLFRUPkLM         7.72         8.17   
2  83B76C01XPvAibaEXe/lOccskaOiO2K46r7t4qnt         5.03         4.53   
3  91F785ABXPvAibaEXe/lOccskaOiO5y4GbVvuRQu         7.03         6.11   
4  007C275DXPvAibaEXe+TFgEDwYNnveOOmOYeYzF6         6.63         7.06   

   diemnamhoc3  diemnamhoc4  diemnamhoc5  diemnamhoc6  drlnam1  drlnam2  \
0         6.55         6.89         7.86          NaN     86.0     78.0   
1         8.30         8.10         7.40          NaN     98.0     94.0   
2         2.46          NaN          NaN          NaN     64.0     56.5   
3         6.76         6.41         7.14          0.0     77.5     53.0   
4         8.15         7.09         1.20          4.7     91.5     86.0   

   drlnam3  drlnam4  drlnam5  drlnam6 label  
0     85.0     64.5     75.0      NaN   Khá  
1     82.0     71.0     65.5      NaN   Rớt  
2    -14.0      NaN      NaN      NaN   Rớt  
3     66.5     61.0     68.0     55.0   Rớt  
4     78.5     70.5     60.5     77.4   Rớt

In [ ]:
df_diem = df_diem[df_diem['label'] != 'Chưa tốt nghiệp']

In [ ]:
print(df_diem['label'].unique())

['Khá' 'Rớt' 'Trung bình khá' 'Trung bình' 'Giỏi' 'Xuất sắc']


Cột diemnamhoc5 và diemnamhoc6 chứa điểm trung bình năm học của sinh viên.
Quan sát thấy:

Nếu giá trị trong diemnamhoc5 hoặc diemnamhoc6 là 0, các giá trị ở những năm học sau đó đều là null. Điều này có thể do:


*   Sinh viên đã tốt nghiệp
*   Sinh viên đã bỏ học (không có dữ liệu tiếp theo)



In [ ]:
#Kiểm tra thấy các sinh viên có diemnamhoc5 và diemnamhoc6 nếu = 0 thì các điểm năm học sau đó đều là null (có thể do sinh viên đã tốt nghiệp hoặc do bỏ học)
df_diem.loc[df_diem['diemnamhoc5'] == 0, 'diemnamhoc5'] = np.nan
df_diem.loc[df_diem['diemnamhoc6'] == 0, 'diemnamhoc6'] = np.nan
df_diem.loc[df_diem['diemnamhoc4'] == 0, 'diemnamhoc4'] = np.nan
df_diem.loc[df_diem['diemnamhoc3'] == 0, 'diemnamhoc3'] = np.nan
df_diem.loc[df_diem['diemnamhoc2'] == 0, 'diemnamhoc2'] = np.nan
df_diem.loc[df_diem['diemnamhoc1'] == 0, 'diemnamhoc1'] = np.nan

df_diem.loc[df_diem['drlnam1'] == 0, 'drlnam1'] = np.nan
df_diem.loc[df_diem['drlnam2'] == 0, 'drlnam2'] = np.nan
df_diem.loc[df_diem['drlnam3'] == 0, 'drlnam3'] = np.nan
df_diem.loc[df_diem['drlnam4'] == 0, 'drlnam4'] = np.nan
df_diem.loc[df_diem['drlnam5'] == 0, 'drlnam5'] = np.nan
df_diem.loc[df_diem['drlnam6'] == 0, 'drlnam6'] = np.nan

## Phân cụm theo từng năm (tất cả các nhãn)

In [ ]:
from sklearn.cluster import KMeans, DBSCAN, MeanShift, AgglomerativeClustering

In [ ]:
hierarchical = AgglomerativeClustering(n_clusters=3)

In [ ]:
def plot_clusters(X, labels, title):
    # Check if X has more than one column
    if X.shape[1] > 1:
        plt.scatter(X.iloc[:, 0], X.iloc[:, 1], c=labels, s=30, cmap='viridis')
    else:
        # If only one column, plot against index
        plt.scatter(X.index, X.iloc[:, 0], c=labels, s=30, cmap='viridis')
    plt.title(title)
    plt.show()

In [ ]:
def plot_clusters_1D(X, labels, title):
    plt.scatter(X, np.zeros_like(X), c=labels, s=30, cmap='viridis')
    plt.title(title)
    plt.yticks([])  # Ẩn trục y vì không cần thiết
    plt.xlabel('Feature')  # Nhãn cho trục x
    plt.show()

In [ ]:
from sklearn.mixture import GaussianMixture

In [ ]:
#Phân cụm điểm cho từng năm học
from sklearn.cluster import KMeans
#Điểm
def cluster_namhoc(df):
  for i in range(1,7):
    X  = df_diem[[f'diemnamhoc{i}']].dropna()
    print('----------------------------------------------')
    print(f'Phân cụm cho điểm năm {i}')
    print(len(X))
    kmeans = KMeans(n_clusters=3, random_state=0).fit(X)
    print(f'Centers found for {i} years:')
    print(kmeans.cluster_centers_)
    globals()[f'centers{i}'] = kmeans.cluster_centers_
    globals()[f'pred_label{i}'] = kmeans.predict(X)
    print(pd.Series(kmeans.predict(X)).value_counts())

#Điểm rèn luyện
def cluster_drl(df):
  for i in range(1,7):
    X  = df_diem[[f'drlnam{i}']].dropna()
    print('----------------------------------------------')
    print(f'Phân cụm cho điểm rèn luyện năm {i}')
    print(len(X))
    kmeans = KMeans(n_clusters=3, random_state=0).fit(X)
    print(f'Centers found for {i} years:')
    print(kmeans.cluster_centers_)
    globals()[f'centers_drl{i}'] = kmeans.cluster_centers_
    globals()[f'pred_label_drl{i}'] = kmeans.predict(X)
    print(pd.Series(kmeans.predict(X)).value_counts())

In [ ]:
cluster_drl(df_diem)

----------------------------------------------
Phân cụm cho điểm rèn luyện năm 1
4899
Centers found for 1 years:
[[51.95558959]
 [87.52326151]
 [72.46710526]]
2    2204
1    2042
0     653
Name: count, dtype: int64
----------------------------------------------
Phân cụm cho điểm rèn luyện năm 2
4673
Centers found for 2 years:
[[35.07816377]
 [89.13623674]
 [72.18091973]]
2    2479
1    1791
0     403
Name: count, dtype: int64
----------------------------------------------
Phân cụm cho điểm rèn luyện năm 3
4464
Centers found for 3 years:
[[72.36205859]
 [31.94590164]
 [89.95905819]]
0    2492
2    1667
1     305
Name: count, dtype: int64
----------------------------------------------
Phân cụm cho điểm rèn luyện năm 4
4266
Centers found for 4 years:
[[92.52298101]
 [53.5670826 ]
 [75.01984714]]
2    2486
0    1211
1     569
Name: count, dtype: int64
----------------------------------------------
Phân cụm cho điểm rèn luyện năm 5
2817
Centers found for 5 years:
[[57.68303571]
 [70.0966892

In [ ]:
cluster_namhoc(df_diem)

----------------------------------------------
Phân cụm cho điểm năm 1
4858
Centers found for 1 years:
[[3.20633136]
 [5.84955817]
 [7.54057343]]
2    2145
1    2037
0     676
Name: count, dtype: int64
----------------------------------------------
Phân cụm cho điểm năm 2
4628
Centers found for 2 years:
[[5.997534  ]
 [2.75962704]
 [7.64360048]]
2    2508
0    1694
1     426
Name: count, dtype: int64
----------------------------------------------
Phân cụm cho điểm năm 3
4438
Centers found for 3 years:
[[6.03577778]
 [7.71212243]
 [2.62023529]]
1    2470
0    1541
2     427
Name: count, dtype: int64
----------------------------------------------
Phân cụm cho điểm năm 4
4239
Centers found for 4 years:
[[2.72464368]
 [7.99218508]
 [6.17835677]]
1    2453
2    1351
0     435
Name: count, dtype: int64
----------------------------------------------
Phân cụm cho điểm năm 5
2691
Centers found for 5 years:
[[8.21960133]
 [2.64241096]
 [6.03697929]]
0    1510
2     817
1     364
Name: count, dty